default: &default
  adapter: postgresql
  encoding: unicode
  database: homework_5
  username: postgres
  password: Potato

development:
  <<: *default

test: &test
  <<: *default
  database: rorlevelup2019_test
