default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: Tomato
  
development:
  <<: *default

test: &test
  <<: *default
  database: flode_test
